Added N. Lohmann's JSON library and P. Boettcher's JSON Schema validation library to the stack
JCSDA/jedi-stack pull request #144
Opened 2020-09-09 22:15 UTC by wsmigaj

## Description

This PR adds a script building the https://github.com/pboettch/json-schema-validator library for JSON Schema validation and its dependency, the https://github.com/nlohmann/json library for JSON parsing. It also adds modules defining environment variables used by CMake's `find_package()` command to locate these libraries.

### Issue(s) addressed

- fixes #143

## Dependencies

None

## Impact

None

2020-09-09 22:25 UTC, wsmigaj commented on buildscripts/config/config_cheyenne.sh
> +export          STACK_BUILD_JSON=Y
I wasn't sure whether to set these variables to Y or N in the scripts used on particular HPC machines. I'm happy to switch them to N.

2020-09-09 22:25 UTC, wsmigaj commented on buildscripts/build_stack.sh
> +build_lib JSON json 3.9.1
I've put the new libraries in the "Optional extensions" section because they won't be required to build JEDI; however, I'd like them to be installed at least on the virtual machines used for continuous integration.

2020-09-09 22:25 UTC, wsmigaj commented on buildscripts/libs/build_json-schema-validator.sh
> +    module load json
This defines the `nlohmann_json_DIR` variable that is used by CMake to find N. Lohmann's JSON library, a necessary prerequisite for building `json-schema-validator`. This doesn't happen in the else branch in lines 26-28. Is that a problem?

2020-09-09 22:25 UTC, wsmigaj commented on modulefiles/apps/jedi/clang-mpich.lua
> +load("json")
I hope it's OK to load the new modules in these scripts -- let me know if not. I've noticed though that this is not done  in https://github.com/JCSDA/jedi-stack/pull/128 (the PR adding support for gsl-lite).

2020-09-09 22:25 UTC, wsmigaj commented on modulefiles/core/json/json.lua
> +setenv("nlohmann_json_DIR", base)
I'm defining the `..._DIR` variable as well as `..._ROOT` because the top-level `CMakeLists.txt` file in `json-schema-validator` sets the CMake minimum version to 3.2, and as a result CMake uses the old policy of disregarding `..._ROOT variables`, emitting the warning
> CMake Warning (dev) at CMakeLists.txt:66 (find_package):
>  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
>  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
>  command to set the policy and suppress this warning.

2020-09-10 17:35 UTC, mmiesch commented on buildscripts/config/config_cheyenne.sh
> +export          STACK_BUILD_JSON=Y
This is sufficient - we're changing this in the [next PR](https://github.com/JCSDA/jedi-stack/pull/138) anyway to avoid having to set these flags for each machine

2020-09-10 17:39 UTC, mmiesch commented on modulefiles/apps/jedi/clang-mpich.lua
> +load("json")
For this purpose I think it is ok.  Where it gets to be a problem is for things like netcdf when there are several versions around, including jedi-stack and native, and the one you want is not necessarily the default one.

2020-09-10 17:43 UTC, mmiesch commented on buildscripts/config/config_custom.sh
> +export STACK_BUILD_JSON_SCHEMA_VALIDATOR=Y
I'd rather not set these to Y in the custom config file - for that one I like to explicitly select what I want to install

2020-09-10 18:15 UTC, mmiesch commented
Looks great - thanks @wsmigaj!  I made just one more minor change.  On my Mac I install cmake via homebrew so it's not a module.  The same is true on a few other systems.  So, I changed the `module load`s of cmake to `module try-load`s.  This installs on my Mac and I tested it with the `feature/json_schema_generation` branch of oops and the packages were found.

2020-09-10 18:15 UTC, mmiesch approved these changes

2020-09-10 18:19 UTC, mmiesch commented
Just one more question - the packages that ecbuild finds are:
```
 * nlohmann_json
 * nlohmann_json_schema_validator
```
But, in the title of this PR, I thought the validator was from P. Boettcher, not Lohmann...

2020-09-10 18:25 UTC, wsmigaj commented
Quoting https://github.com/pboettch/json-schema-validator/blob/master/README.md:

> Niels Lohmann et al develop a great JSON parser for C++ called JSON for Modern C++. This validator is based on this library, hence the name.

I guess by the same logic we should rename jedi to ecmwf_jedi, since it's based on eckit ;-).

2020-09-10 18:29 UTC, mmiesch commented
> I guess by the same logic we should rename jedi to ecmwf_jedi, since it's based on eckit ;-).

Don't mention that to Yannick :smile:

2020-09-23 20:08 UTC, markjolah approved these changes
Approve modulo small changes.  Let me know if there are any questions.

2020-09-23 20:08 UTC, markjolah commented on buildscripts/libs/build_json-schema-validator.sh
> +    module load json
The `module load json` should use a `try-load`, as some systems may have that package already available on the base system

2020-09-23 20:08 UTC, markjolah commented on buildscripts/config/config_gentoo.sh
> +export STACK_BUILD_JSON_SCHEMA_VALIDATOR=Y
These should be `N` here.  In general, it's probably safest to default to `N` for all these scripts in the `config` directory.  I was trying to keep only Fortran packages that produce `.mod` files as `Y` here, but it seems that a few non-Fortran `Y` have crept in.  Sorry for any confusion.

2020-09-23 20:13 UTC, markjolah requested changes
I'll change this to "request changes" just to make sure it doesn't get merged before changes are made, but they are just a few small items.

2020-09-25 09:24 UTC, wsmigaj reviewed
@markjolah Many thanks for your helpful comments -- I've modified the scripts as you suggested. I've also adjusted the CMake invocation used to build `json-schema-validator` (which unlike `json` is not a header-only library) to enable optimisations and produce a shared library. This seems to be in line with what happens with other libraries, such as `libjpeg`.

2020-09-25 09:24 UTC, wsmigaj commented on buildscripts/config/config_gentoo.sh
> +export STACK_BUILD_JSON_SCHEMA_VALIDATOR=Y
OK -- I've replaced `Y`s with `N`s.

2020-09-25 09:24 UTC, wsmigaj commented on buildscripts/libs/build_json-schema-validator.sh
> +    module load json
OK -- done.

2020-09-25 09:24 UTC, wsmigaj commented on modulefiles/core/json/json.lua
> +setenv("nlohmann_json_DIR", base)
Thanks for pointing this out -- I've adjusted the path as you suggested. At the moment, the path contains a hardcoded `lib`. Do you think the module should try to determine if the given system uses `lib` or `lib64`?

2020-09-29 16:41 UTC, mmiesch commented
@markjolah - Are you happy with this now?  Shall we merge it?

2020-10-08 17:35 UTC, markjolah approved these changes

2020-10-08 17:42 UTC, markjolah commented on modulefiles/core/json/json.lua
> +setenv("nlohmann_json_DIR", base)
@wsmigaj Sorry for not getting back sooner.  The `lib` vs `lib64` issue is one of the reasons to use the `<pkg>_ROOT` variable, since you just need the prefix.  

Keep in mind that jedi-stack works in a context where scripts are installing packages to custom prefix directory  where the `lib` vs `lib64` distinction is not system-enforced.  For other packages with this problem, we've forced it to install to `lib` in the build script and then used `lib` explicitly in Lua module code.  That's what you did in the updated version so it looks OK to me.

2020-10-08 17:46 UTC, merged

2020-10-09 08:15 UTC, wsmigaj commented on modulefiles/core/json/json.lua
> +setenv("nlohmann_json_DIR", base)
Ah, that's good to know -- thanks!

2020-10-09 08:15 UTC, wsmigaj commented
Thanks a lot for merging this in, @mmiesch.