add FMS to the stack
JCSDA/jedi-stack pull request #160
Opened 2020-09-26 14:58 UTC by aerorahul

## Description

This PR adds GFDL-FMS as an option to be built in the jedi-stack.
GFDL FMS is used in GFDL based models FV3 and MOM6.
FV3 and MOM6 are dynamical cores for the atmosphere and ocean in the UFS and GEOS Earth System Models.

### Issue(s) addressed

closes #159 

## Dependencies

None

## Impact

fv3-bundle and soca-bundle can test their bundles using the FMS from the authoritative repo.
This reduces burden on JCSDA to sync, and maintain their FMS forks, which are usually stale.
Changes may be expected due to an update in the FMS library.  Impact is unknown until tested.

2020-09-28 13:42 UTC, danholdaway requested changes

2020-09-28 13:42 UTC, danholdaway commented on buildscripts/libs/build_fms.sh
> +gitURL="https://github.com/noaa-gfdl/fms"
I don't think this should be hardwired to the GFDL repo, see e.g. https://github.com/JCSDA/jedi-stack/blob/develop/buildscripts/libs/build_atlas.sh where we can optionally build the fork or original code. Right now you would not be able to run SOCA with the GFDL repo because of the changes @guillaumevernieres added for the adjoint halo exchange and wants to add for the name length. We plan to continue working from the fork.

2020-09-28 13:54 UTC, aerorahul commented on buildscripts/libs/build_fms.sh
> +gitURL="https://github.com/noaa-gfdl/fms"
I thought the point was to use the upstream repo. But, sure, I can make the change to provide a repository of choice.

2020-09-28 13:55 UTC, danholdaway commented
I've created a branch called release-stable-new in the JCSDA fork of FMS. This is GFDL master with our local changes for more tracers, halo exchange for mom6 domain and some build things that Mark O added. Now there is no longer conflicts with upstream but the ecbuild stuff is gone. We should try to build this branch with the stack and test with fv3-jedi and soca. If it works OK I'll rename it to release-stable and we'll move to always building as a module instead of in the bundle.

2020-09-28 13:59 UTC, danholdaway commented on buildscripts/libs/build_fms.sh
> +gitURL="https://github.com/noaa-gfdl/fms"
I think the main thing, for me at least, is to get away from the continual conflicts with the upstream because of diverged CMakeLists files. That should make it easier to more frequently push changes to GFDL.

2020-09-28 13:59 UTC, aerorahul commented
> I've created a branch called release-stable-new in the JCSDA fork of FMS. This is GFDL master with our local changes for more tracers, halo exchange for mom6 domain and some build things that Mark O added. Now there is no longer conflicts with upstream but the ecbuild stuff is gone. We should try to build this branch with the stack and test with fv3-jedi and soca. If it works OK I'll rename it to release-stable and we'll move to always building as a module instead of in the bundle.

The PR is updated to provide a source for the repository.

2020-09-28 13:59 UTC, danholdaway approved these changes

2020-09-28 14:06 UTC, mmiesch commented
Today I'm planning to build a new stack on Discover to see if it solves the problem we're having with the current intel stack (incompatible modules in ufo).   As I am doing that, I'll add FMS.  So, I'll defer my review until then after I confirm it works.

2020-09-28 19:35 UTC, mmiesch commented on buildscripts/libs/build_fms.sh
> +export CFLAGS="-fPIC -w"
Did we want the `+=` here to support global config flags as in the other scripts?

2020-09-28 19:42 UTC, aerorahul commented on buildscripts/libs/build_fms.sh
> +export CFLAGS="-fPIC -w"
yep. good catch. fixed in c994345.

2020-09-28 19:43 UTC, mmiesch commented
This looks great - it works for me on Discover.  But, it currently creates a module called `fms/noaa-gfdl-master`.  This may be fine, but I think tagged versions are usually better for modules so the user knows exactly what he or she is getting.  And, as @danholdaway mentioned, we may want to change this to a release-stable branch (why -new?)

2020-09-28 19:46 UTC, aerorahul commented
> This looks great - it works for me on Discover. But, it currently creates a module called `fms/noaa-gfdl-master`. This may be fine, but I think tagged versions are usually better for modules so the user knows exactly what he or she is getting. And, as @danholdaway mentioned, we may want to change this to a release-stable branch (why -new?)

wouldn't the `jcsda::release-stable` modulefile be named `fms/jcsda-release-stable` similar to `eckit`, `fckit` and `atlas` modulefiles?

2020-09-28 19:53 UTC, mmiesch commented
> wouldn't the `jcsda::release-stable` modulefile be named `fms/jcsda-release-stable` similar to `eckit`, `fckit` and `atlas` modulefiles?

The recommended practice is to use release-stable when building the ecmwf forks with a bundle but to use tagged versions when creating modules.  So, for example, the available versions of ecbuild on Discover are:
```
mmiesch@discover32:/discover/swdev/jcsda/modules/modulefiles/apps/jedi/intel-impi> module avail ecbuild

-------------------------------------------------------- /discover/swdev/jcsda/modules/modulefiles/core ---------------------------------------------------------
   ecbuild/jcsda-develop         ecbuild/jcsda-3.3.0.jcsda3    ecbuild/jcsda-3.3.2.jcsda2
   ecbuild/jcsda-3.1.0.jcsda3    ecbuild/jcsda-3.3.2.jcsda1    ecbuild/jcsda-3.3.2.jcsda3 (L,D)
```

All of these were `release-stable` at one point but this freezes the development in time.

2020-09-28 20:05 UTC, mmiesch commented
Ok - an `fms` module is now available to go with the `jedi/intel-impi`, `jedi/intel-impi/19.1.2.254`, and `jedi/gnu-impi` stacks on Discover.  But, for now you have to load it manually.  For example:
```
module load jedi/intel-impi
module load fms
```
We could include it in the default modules but first I think we need to add some logic to fv3-bundle to detect whether it's there or not and, if so, skip the build.

2020-09-28 20:28 UTC, mmiesch commented
On second thought - maybe it would indeed be best to just use `master` instead of a tagged version, at lease for the `noaa-gfdl` source - I see that there have been nearly 1000 commits since their last release over a year ago!

So, the only remaining question I have is what to use for the default in `build_stack.sh`.  Can you build `fv3-bundle` and `soca-bundle` with `noaa-gfdl/master`?  If not, we should make our fork the default.  And, should we tag our current release-stable version?

2020-09-28 23:36 UTC, aerorahul commented
I am 99% confident that NOAA-gfdl master will not work with the bundles. 
I can make the JCSDA fork and release-stable the defaults, if that is the consensus. 
Just let me know.

2020-09-29 01:48 UTC, danholdaway commented
@mmiesch it's release-stable-new for now but once you install the module and we test with fv3-jedi and soca I would change release-stable to release-stable-ecbuild and rename release-stable-new to release-stable. From then on JCSDA release-stable should be the default. Let me know when there is a module on Discover with release-stable-new and I will make the changes necessary with fv3-jedi to be able to build with the module.

2020-09-29 13:07 UTC, aerorahul commented
@mmiesch @danholdaway 
I made the change in `build_stack.sh` to use `jcsda::release-stable` 
When installing on Discover, please install release-stable-new for testing with fv3-bundle and soca-bundle.
If the tests pass, then @danholdaway can merge/replace release-stable in the repo with release-stable-new and there will be no change required in the jedi-stack repo.

2020-09-29 16:13 UTC, mmiesch commented
Thanks @aerorahul - I just made a small change to add the FMS flags to the container config files.  In my opinion, the `choose_modules.sh` script is the most convenient for interactively setting up modules but the containers use their own automated procedure and do not call `choose_modules.sh`

2020-09-29 16:13 UTC, mmiesch approved these changes

2020-09-29 16:14 UTC, mmiesch commented
So, before I merge this, just one more question - should we install fms in the containers?

2020-09-29 16:31 UTC, mmiesch commented
Actually, I'll go ahead and merge this - we can decide later whether to include it in the containers - there will be another PR in the future with container updates.

2020-09-29 16:32 UTC, merged

2020-09-29 17:45 UTC, mmiesch commented
Ok @danholdaway @aerorahul - I still think a tagged version is preferable for modules but in any case there are now two fms modules available for each of the `jedi/gnu-impi`, `jedi/intel-impi`, and `jedi/intel-impi/19.1.2.254` stacks, namely `fms/noaa-gfdl-master` and `fms/jcsda-release-stable-new`, with the latter being the default.   Currently fms is not auto-loaded in the top meta-module because I thought it might break existing builds.  When fv3-bundle and soca-bundle are ready with the cmake check let me know and we can arrange for fms to be loaded with the rest of the modules.

2020-09-30 00:13 UTC, rickgrubin commented
Seeing the following error on the `develop` branch on orion, S4, and my mac:

**orion**:
```
-- Detecting Fortran compiler ABI info - done
-- Check for working Fortran compiler: /apps/intel-2020/intel-2020/compilers_and_libraries_2020.0.166/linux/mpi/intel64/bin/mpiifort - skipped
-- Checking whether /apps/intel-2020/intel-2020/compilers_and_libraries_2020.0.166/linux/mpi/intel64/bin/mpiifort supports Fortran 90
-- Checking whether /apps/intel-2020/intel-2020/compilers_and_libraries_2020.0.166/linux/mpi/intel64/bin/mpiifort supports Fortran 90 - yes
CMake Error at CMakeLists.txt:23 (include):
  include could not find load file:

    ecbuild_system


CMake Error at CMakeLists.txt:25 (ecbuild_requires_macro_version):
  Unknown CMake command "ecbuild_requires_macro_version".

```


**S4**:
```
-- Detecting Fortran compiler ABI info - done
-- Checking whether /opt/intel/19/compilers_and_libraries_2019.5.281/linux/mpi/intel64/bin/mpiifort supports Fortran 90
-- Checking whether /opt/intel/19/compilers_and_libraries_2019.5.281/linux/mpi/intel64/bin/mpiifort supports Fortran 90 - yes
CMake Error at CMakeLists.txt:23 (include):
  include could not find load file:

    ecbuild_system


CMake Error at CMakeLists.txt:25 (ecbuild_requires_macro_version):
  Unknown CMake command "ecbuild_requires_macro_version".
```

**mac (same for clang v11.0.3 and GNU v10.2.0; below is with the GNU compilers)**:
```
-- Detecting Fortran compiler ABI info - done
-- Checking whether /Users/grubin/opt/modules/gnu-10.2.0/openmpi/4.0.3/bin/mpifort supports Fortran 90
-- Checking whether /Users/grubin/opt/modules/gnu-10.2.0/openmpi/4.0.3/bin/mpifort supports Fortran 90 - yes
CMake Error at CMakeLists.txt:23 (include):
  include could not find load file:

    ecbuild_system


CMake Error at CMakeLists.txt:25 (ecbuild_requires_macro_version):
  Unknown CMake command "ecbuild_requires_macro_version".
```

2020-09-30 18:48 UTC, mmiesch commented
I'm getting this now too on my Mac, although I did not see it on Discover